### ISSUE TITLE
Can't build Win64 due to inline assembly

### ISSUE THREAD

**Issue by ghost** [swistakm/gorilla-audio#7]
**EDIT: Sorry, just realised this is a modified version of gorilla audio, github doesn't have a way of deleting issues.**

The title says it all, I set CMAKE to VS2017 Win64 and got a load of errors claiming `__asm` wasn't supported in the current architecture.

**Comment by swistakm** [comment]
I will close this but tell me if this version works for you? I remember having similar problem and I think I have just updated upstream version of libvorbis or libogg and it worked fine. If you give me more output from compiler we can try to fix it together.

**Comment by ghost** [comment]
No, didn't work. The issues are with libogg.
They're pretty much all just:
`error C4235: nonstandard extension used: '__asm' keyword not supported on this architecture`

**Comment by swistakm** [comment]
Trie to look into this but there is no `__asm` keyword anywhere in libogg sources. Libvorbis has some asm code but it should be disabled on architecture other than 32bit. Look into `ext/libvorbis/lib/os.h` header. 
It may be something wrong with cmake invocation.

I close this issue for now. Feel free to reopen if you find anything new or want to provide more details.
